### ISSUE TITLE
RDF version should have some section headers as RDF/N3 comments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#21] opened 2015-03-13 17:33 UTC
```
The normative page's headers could be rendered in RDF as N3 comments.
```

Original issue reported on code.google.com by `morris.bob` on 23 Aug 2012 at 7:38

**Comment by baskaufs** [comment] 2018-07-16 10:58
I don't really understand what this issue is about.  [Section 4.2.2](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#42-general-metadata) of the Standards Documentation Specification provides terms to describe documents in machine-readable serializations.  However, I'm not sure what putting headers in an RDF document as comments would accomplish, since the comments would be ignored by parsers of the document.

**Comment by baskaufs** [comment] 2018-07-17 12:24
@ramorrismorris can you clarify what this issue is actually proposing?

**Comment by ramorrismorris** [comment] 2018-07-17 16:47
Ummm...neither do I, at least in part because the 2012 version seemed to have been closed without much remaining explanation. I don't even fully understand what our practice currently is in such a case.

**Comment by baskaufs** [comment] 2018-07-17 17:01
OK, well if we aren't actually clear about what the issue is, I'm just going to close it.  It could always be reopened at some point if it is discovered to be significant.

**Closed by baskaufs** 2018-07-17 17:01 UTC
Labels: Component-RDF, Milestone-RDF, Priority-Medium, Type-Defect
