### ISSUE TITLE
Consider fungal parts as additions to Views CV

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#240] opened 2022-05-02 02:21 UTC
> ...
> no fungi ... (eg. thallus, fruiting body, vegetative reproductive structure, mycelium, symbiont)
> ...
> The controlled vocabulary is intended to be extensible, so we'd be happy to add fungi if someone will suggest the terms, test with images, etc.

@baskaufs What would it take to add the above terms to your vocabulary?

A) If it is a matter of the amount of information present in this [overview](https://github.com/tdwg/ac/blob/master/views/code/subjectPart/subjectPart_cv.csv) and the [first two links in your initial post](https://github.com/tdwg/material-sample/issues/24#issue-1208803024), I could provide this for the above terms and learn along the way about how to construct and publish vocabularies correctly. 

B) Though, there wouldn't be any testing and community agreement supporting the contributed terms. For that, the vocabularies need the mycologists and lichenologists eg. from the citizen science initiatives for fungi. 

C) This is the [Task Group](https://github.com/tdwg/ac/blob/master/views/README.md) you were mentioning. Your report for 2021 suggests that you are wrapping up and might not want to reopen the process.

Not sure where the balance in all of this is right now.

_Originally posted by @jbstatgen in https://github.com/tdwg/material-sample/issues/24#issuecomment-1108129167_

**Comment by baskaufs** [comment] 2022-05-02 02:26
@jbstagen We are considering additions for some other groups, such as mosses and ferns. So it isn't too late to add fungi, particularly if we stick to the obvious terms and add niche/controversial ones later if there is additional demand and discussion. 

We do want to wrap this up, but have considered the possibility of additional terms that are discovered to be missing during the implementation testing phase (which is what we are trying to finish now).

**Comment by jbstatgen** [comment] 2022-05-04 07:57
Thanks Steve! Working on it.

**Comment by jbstatgen** [comment] 2022-05-18 18:16
The table with the evolving vocabulary can be found here:
[https://docs.google.com/spreadsheets/d/1xUUDNd6XdH0g4QlfOQ7K-BpFcUffAB4PSOfMXOuKB4I/edit#gid=0](https://docs.google.com/spreadsheets/d/1xUUDNd6XdH0g4QlfOQ7K-BpFcUffAB4PSOfMXOuKB4I/edit#gid=0)

Currently it has definitions for 
* mycelium
* thallus
* fruiting body
* vegetative reproductive structure
* symbiont

As far as the terms exist, the corresponding terms and definitions are shown from the obo FAO ontology for [Fungal gross anatomy](https://www.ontobee.org/ontology/FAO).

Several terms from the FAO ontology might be added if they are not too fine-scale. These are shown at the bottom of the list in the spreadsheet.

**Comment by baskaufs** [comment] 2022-05-23 20:37
Thanks for your work, @jbstatgen ! I've started by adding the five general terms as rows 44 through 48 in [this version of the subjectPart table](https://github.com/tdwg/ac/blob/84d0a2eff86fcbbbd59480dd455cbf1906ee3ac8/views/code/subjectPart/subjectPart_cv.csv). We can consider the other narrower terms you suggested after we see how this goes.

I didn't do much of any editing except to turn the ontology references into IRIs.

A few questions (sorry about my ignorance about fungi):
1. For "fruiting body", you had "narrower?" in the `skos_broader` column. Is it a narrower term of one of the others? if so, which one? 
2. I'm unclear about the intended relationship between `mycelium` and `thallus`. mycelium is defined as "a mass of hyphae constituting the body (thallus) of a fungus". That would imply to me that the thallus is part of the mycelium. How is the mycelium related to a whole organism (another possible value)?
3. You say in the Usage for thallus that it can be used for bryophytes and ferns. If so, how is it related to the p0037 already in the table for those groups? If they are the same, we should have a definition that applies to both groups. If they are different, then we need different labels and controlled value strings.
4. I am a bit confused about symbiont. It seems like it's defined based on a relationship that it has with other organisms, rather than morphology. If that's accurate, then it seems like working out some kind of Darwin Core ResourceRelationship instance for the involved organisms would be the way to go. 

I think as is the case with https://github.com/tdwg/ac/issues/235#issuecomment-1135066520, the actual test would be to come up with a set of typical fungi images and try to test the terms out on them. If it's clear how to use these values, then we are good to go. If not, then we need to re-evaluate.

**Comment by baskaufs** [comment] 2022-07-15 15:52
Since these issues weren't resolved nor was any testing completed prior to the end of implementation testing, these proposed terms have been [archived as candidate terms](https://github.com/tdwg/ac/tree/master/views/candidate_terms/fungi), with the potential of being added to the vocabularies when additional work and testing on them has been completed.

**Comment by baskaufs** [comment] 2022-07-18 14:06
Reopening since @jbstatgen is interested in actively moving this forward.

**Comment by jbstatgen** [comment] 2022-07-20 06:49
Thanks @baskaufs for reopening the issue. As I understand from our exchange off-site, the fungal terms won't be in the first version of the vocabulary. However, within Audubon Core a process by its maintenance group is in place for regularly updating vocabularies. Thus, we can submit them as part of a regular update later.

**Comment by jbstatgen** [comment] 2022-07-20 07:23
In answer to the questions above in https://github.com/tdwg/ac/issues/240#issuecomment-1135115594

> 1. For "fruiting body", you had "narrower?" in the skos_broader column. Is it a narrower term of one of the others? if so, which one?

The fruiting bodies of basidiomycetes always and lichenized ascomycetes generally are sexual reproductive structures. However, for non-lichenized ascomycetes, which I don't know sufficiently, fruiting bodies can be reproductive structures of sexual or asexual origin. 

Thus, within basidiomycetes, fruiting body is generally used in a "narrower" sense, that is, it refers only to a sexual structure (the "mushroom", a sporocarp or sporom).

In the context here, my suggestion is to use the term in the more general scope, ie. including both sexual and asexual reproduction, since we are defining high-level concepts that

* are applicable to all fungi, at least to basidio- and ascomycetes,
* can be used by non-specialists and 
* can be applied to images possibly taken in the field without in-depth background investigations (eg. microscopy, culturing).

Thus, I would keep the definition as it is and e.g. "conidioma" (an asexual reproductive structure) as one of the provided examples.

Later on, more specialized terms, as eg. sporocarp/sporom, can be added.

**Comment by jbstatgen** [comment] 2022-07-20 08:40
> 3. You say in the Usage for thallus that it can be used for bryophytes and ferns. If so, how is it related to the p0037 already in the table for those groups? If they are the same, we should have a definition that applies to both groups. If they are different, then we need different labels and controlled value strings.

Both terms should be merged. My suggestion for a definition that applies generally is "**A relatively simple vegetative body not differentiated into stems, roots, and leaves**", adding under usage "Thalli are found in diverse groups such as algae (cp. kelp), liverworts, bryophytes, fungi, including lichens, and some slime molds". 

We might add "ferns", though en/wikipedia says "The gametophyte of some non-thallophyte plants – clubmosses, horsetails, and ferns is termed "prothallus".", see [https://en.wikipedia.org/wiki/Thallus)](https://en.wikipedia.org/wiki/Thallus) and [https://de.wikipedia.org/wiki/Thallus](https://de.wikipedia.org/wiki/Thallus).

In this definition the term is certainly broader than the term "lichen thallus" defined by [http://purl.obolibrary.org/obo/FAO_0000034](http://purl.obolibrary.org/obo/FAO_0000034). I don't think we should refer to FAO_0000034 under "definition_derived_from".

**Comment by jbstatgen** [comment] 2022-07-20 09:00
> 4. I am a bit confused about symbiont. It seems like it's defined based on a relationship that it has with other organisms, rather than morphology. If that's accurate, then it seems like working out some kind of Darwin Core ResourceRelationship instance for the involved organisms would be the way to go.

Yes, the key concept of a symbiont is based on its relationship. However, in the context here, my suggestion is that the term is used as a pseudo morphological term. 

Compare the situation for chloroplasts, they have a symbiotic origin, nevertheless, you wouldn't use a DwC ResourceRelationship to refer to a chloroplast. Similarly with the symbionts of fungi, in practical use, you might just state that part of an image is a "symbiont", eg. the root or the algal/cyanobacterial cells that are visible. 

My impression is that if you would use a ResourceRelationship, then you would want/need to specify the symbiotic partner. However in the field that often is not possible. Do the roots to which the mycelium is attached that gave rise to the mushroom that you dug up belong to the oak on the right or the pine on the left? Are the green unicellular blobs in the (ad hoc) cross-section green algae or cyanobacteria, or both? You might know that in theory this lichen or mushroom species has x, y, z as symbiotic partners. However, can you really observe that and determine the taxon based on the image and/or the situation in which the image was taken?

Should you go deeper and investigate, which symbiotic partner it is, then it makes sense to connect a different taxon via a ResourceRelationship. Also, should you have sampled/photographed the symbiotic partner specifically, you would connect the samples/images of the two symbiotic partners via a ResourceRelationship.

**Comment by edwbaker** [comment] 2024-02-21 19:04
Following discussion at the 2024 Working Group meeting, I am closing this as we do not have the capacity or expertise in the Maintenance Group to address this at present. We are open to reopening this if there is sufficient interest to create a Task Group.

**Closed by edwbaker** 2024-02-21 19:04 UTC
Labels: views
